name: Node.js CI

on:
  push:
    branches: ["shell"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"

      - run: cd build && npm install && npm run build

      - name: Commit report
        run: |
          if [ -n "$(git status --porcelain)" ]; then
           git config --global user.name 'Action Committer'
           git config --global user.email 'github-actions[bot]@users.noreply.github.com'
           git commit -am "Action: update built files"
           git push
          fi

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: shell-ci
          publish_dir: ./build


  