name: Node.js CI

on:
  push:
    branches: ["shell"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"

      - run: cd build && npm install && npm run build

      - name: Commit report
        run: |
          if [ -n "$(git status --porcelain)" ]; then
           echo "Changes detected -dry run"
           git status
          fi
  